import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Ubuntu , Poiret_One , Roboto } from "next/font/google";
import "./globals.css";

const ubuntu = Ubuntu({weight : ['300' , '400' , '500' , "700" ] , subsets : ["latin"]})

export const metadata: Metadata = {
  title: "muuza",
  description: "Generated by muuza",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={ubuntu.className}
      >
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
